name: CI for Node.js React Sample App
on: [push]
jobs:
  build: # test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint
